export const POLICY_LAST_UPDATED = "Last updated: October 9, 2026";

export const PRIVACY_SECTIONS: { title: string; body: string }[] = [
  {
    title: "Information processed",
    body: "When you sign in, CheyaVerse processes your Telegram account ID and the profile details Telegram makes available, such as your name and username. The website also processes the messages and account content you choose to create, session and device information used to keep your account secure, and technical request data needed to operate and troubleshoot the service. If you connect GitHub, the service stores your GitHub account details, granted scopes, and access token; the token is encrypted before storage.",
  },
  {
    title: "How information is used",
    body: "Information is used to authenticate your account, provide chat and notification features, manage your media and Library, maintain device sessions, and show the GitHub projects you request. Project information is requested from GitHub when you use those features. If you use AI chat, your prompt and relevant conversation context are sent to the AI provider configured for your account so it can generate a response.",
  },
  {
    title: "Storage and service providers",
    body: "CheyaVerse uses database and file-storage infrastructure to operate the website and store account data and uploaded files. Telegram provides sign-in identity, GitHub provides data when you connect and request it, and browser or push services may process information needed to deliver notifications. These providers handle information under their own privacy terms.",
  },
  {
    title: "AI and connected services",
    body: "AI responses are generated by the provider selected in your account settings. The prompt, relevant chat history, and any GitHub context needed for your request may be sent to that provider. GitHub access tokens and AI provider credentials are not included as prompt text. CheyaVerse does not control how an external provider handles data after receiving a request; review the provider's privacy and data-use terms before using its service.",
  },
  {
    title: "Retention and deletion",
    body: "Chat and account data are retained to provide the website until you remove them or delete your web account. Media displays its expiry information where applicable and is removed according to the service's expiry process; files in Library remain until you remove them or delete your account. Account deletion removes data managed by the CheyaVerse website and requests cleanup of its stored files. It cannot delete copies held by Telegram, GitHub, an AI provider, or another external service.",
  },
  {
    title: "Your choices and security",
    body: "You can manage account settings and device sessions, delete chat messages or files where those controls are available, disconnect GitHub, and delete your web account from Settings. Disconnecting GitHub in CheyaVerse does not revoke the token at GitHub, so revoke it there as well if you no longer want it to be usable. Use a unique password and do not share sign-in links, tokens, or API credentials.",
  },
  {
    title: "Contact",
    body: "For privacy questions or requests about information managed by the website, contact userlinuxorg@gmail.com. Include enough detail to identify the request, but do not email passwords, access tokens, or verification codes.",
  },
];

export const AGREEMENT_SECTIONS: { title: string; body: string }[] = [
  {
    title: "Website service",
    body: "CheyaVerse provides a personal web dashboard with chat, notifications, media and Library tools, account and device settings, optional AI chat, and optional GitHub project views. Features may change or be temporarily unavailable because of maintenance, network conditions, or third-party service interruptions.",
  },
  {
    title: "Account and access",
    body: "Website sign-in uses your Telegram account identity. You are responsible for protecting access to your Telegram account and for activity performed through your signed-in web sessions. Keep your browser and device secure, and sign out or revoke sessions on devices you no longer use.",
  },
  {
    title: "Acceptable use and content",
    body: "Use the website lawfully and respect other people's rights and privacy. You are responsible for the content you submit or upload and must have the rights and permissions needed to use it. Do not attempt to access another person's account or data, interfere with the service, or use it to distribute unlawful or harmful content.",
  },
  {
    title: "Uploads and media",
    body: "Web Library uploads accept image and video files up to 4 MiB per file. Profile cover uploads are limited to 5 MiB. The service displays expiry details for media where applicable; expired files may be removed and may not be recoverable. Keep your own copy of anything you need to retain.",
  },
  {
    title: "Optional GitHub connection",
    body: "When you connect GitHub, you authorize CheyaVerse to request repository information allowed by the credential you provide and for the features you use. Provide only the permissions you need. Disconnect the integration in CheyaVerse and separately revoke its token through GitHub when you no longer want it to have access.",
  },
  {
    title: "Optional AI chat",
    body: "If you use AI chat, your prompt and relevant context may be sent to the AI provider configured for your account. AI responses can be inaccurate, incomplete, or out of date; review them before relying on them or taking action. You are responsible for choosing a provider and reviewing its data-use terms.",
  },
  {
    title: "Account deletion and service availability",
    body: "You may request deletion of your web account through Settings. This removes website-managed account data and does not remove information or copies held by Telegram, GitHub, or external AI providers. CheyaVerse is provided as available and may be updated, interrupted, or discontinued.",
  },
];

export const HELP_FAQS: { q: string; a: string[] }[] = [
  {
    q: "I can't sign in",
    a: [
      "Use the Telegram account you linked to your CheyaVerse profile and complete the sign-in approval flow.",
      "Check that Telegram is available and that your browser allows the site to store session cookies.",
      "If a sign-in request has expired, start again from the login page. Never share an approval code or sign-in link with someone else.",
    ],
  },
  {
    q: "A Library upload did not work",
    a: [
      "Web Library uploads support image and video files up to 4 MiB per file. Profile cover images have a separate 5 MiB limit.",
      "Check the file type, size, connection, and available storage, then retry after any earlier upload has finished.",
      "For previews or playback issues, try a current browser and a commonly supported image or video format.",
    ],
  },
  {
    q: "Media is missing or no longer opens",
    a: [
      "Make sure you are signed in to the account that owns the media.",
      "Check the expiry information shown in Media. Items past their expiry may have been removed.",
      "For Library files, check whether the item or its parent folder was moved or deleted. Reopen the page after your connection is restored.",
    ],
  },
  {
    q: "Notifications are not arriving",
    a: [
      "Allow notifications for CheyaVerse in both your browser's site settings and your device settings.",
      "Check the notification settings in your account and confirm that the browser is not blocking background activity or notifications.",
      "If permission was changed recently, reload CheyaVerse and review the browser's current permission for this site.",
    ],
  },
  {
    q: "My GitHub repositories are missing",
    a: [
      "Open Settings and confirm that the intended GitHub account is connected.",
      "Check that the saved token is active and has permission to read the repositories you want to view. Organization access may require additional authorization at GitHub.",
      "Repository information is requested from GitHub when you open the related pages, so GitHub availability and API limits can affect the results.",
    ],
  },
  {
    q: "AI chat is unavailable or gives an error",
    a: [
      "AI chat requires an active provider configuration in Settings. Check that the selected provider, model, and credential are current.",
      "Provider rate limits, quota, network errors, or temporary outages can interrupt a request. Wait briefly and try again, or use another provider configured for your account.",
      "Only include information you are comfortable sending to the AI provider selected for your account.",
    ],
  },
  {
    q: "How do I remove my data?",
    a: [
      "Use the available controls in Chat, Media, Library, and Settings to remove individual content or manage your account.",
      "Deleting your web account removes data managed by CheyaVerse and stored files where cleanup succeeds. It does not delete copies held by Telegram, GitHub, or an AI provider.",
    ],
  },
];
